env:
    GODOT_VERSION: "4.3"
    GODOT_BUILD: "stable"

on:
    push:
        branches:
            - "*"
        tags:
            - "*"

permissions:
    contents: write

jobs:
    release:
        name: Export and publish game
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: export game
              uses: firebelley/godot-export@v6.0.0
              with:
                  godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}_linux.x86_64.zip
                  godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}_export_templates.tpz
                  use_preset_export_path: true
                  archive_output: true
                  cache: true

            - name: Check that build was successful
              run: |
                  tree export
                  [[ -f export/linux/Linux.zip ]] || (echo "linux build not found"; exit 1)
                  [[ -f export/osx/macOS.zip ]] || (echo "osx build not found"; exit 1)
                  [[ -f "export/windows/Windows Desktop.zip" ]] || (echo "windows build not found"; exit 1)

            # ---- Commands below run for released versions only

            - name: get tag from version
              id: tag_version
              run: |
                  echo "TAG_VERSION=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT

            - name: Upload macOs build to release
              uses: svenstaro/upload-release-action@v2
              with:
                  file: "export/osx/macOS.zip"
                  asset_name: bubbleneck-osx.zip
                  overwrite: true
              if: github.ref_type == 'tag'

            - name: Upload linux build to release
              uses: svenstaro/upload-release-action@v2
              with:
                  file: export/linux/Linux.zip
                  asset_name: bubbleneck-linux.zip
                  overwrite: true
              if: github.ref_type == 'tag'

            - name: Upload windows build to release
              uses: svenstaro/upload-release-action@v2
              with:
                  file: "export/windows/Windows Desktop.zip"
                  asset_name: bubbleneck-windows.zip
                  overwrite: true
              if: github.ref_type == 'tag'
